version: '3'
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        restart: always
        image: client_img
        ports:
            - 3000:3000
        container_name: client
        stdin_open: true
        network_mode: host
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        image: backend_img
        working_dir: /backend
        ports:
            - 5000:5000
        container_name: backend
        network_mode: host